#!/bin/bash

# A shell script for installing supervisord
set -eo pipefail

TMP="$(mktemp -d)"
cleanup() {
    rm -rf "${TMP}"
}
trap cleanup EXIT

RELEASE_URL="https://github.com/ochinchina/supervisord/releases/download/v${SUPERVISORD_VERSION}"
ARCHIVE_FILE="supervisord_${SUPERVISORD_VERSION}_Linux_64-bit.tar.gz"
CHECKSUMS_FILE="supervisord_${SUPERVISORD_VERSION}_checksums.txt"

set -x
curl -sL "${RELEASE_URL}/${CHECKSUMS_FILE}" -o "${TMP}/${CHECKSUMS_FILE}"
curl -sL "${RELEASE_URL}/${ARCHIVE_FILE}" -o "${TMP}/${ARCHIVE_FILE}"
cd "${TMP}"
sha256sum --ignore-missing -c "${CHECKSUMS_FILE}"
tar -C "${TMP}" --strip-components 1 -xzvf "${TMP}/${ARCHIVE_FILE}"
mv "${TMP}/supervisord" /usr/local/bin/supervisord
